version: '3.8'

services:

  db:
    image: mysql:latest # use latest version of mysql
    container_name: db # add a name for the container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment: # add default values, see docs for more info.
      MYSQL_USER: quipper
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_PASSWORD: qwer1234
      MYSQL_DATABASE: quizmaster # create this database on startup
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'

volumes: # add volume to persist dataq.
  my-db: